CREATE TABLE [dbo].[BugLog]
(
	[BugLogID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[BugLogDate] DATETIME NOT NULL,
	[StatusCodeID] INT NOT NULL,
	[UserID] INT NOT NULL,
	[BugLogDesc] TEXT NOT NULL,
	[BugID] INT NOT NULL,
	CONSTRAINT [FK_Bugs_StatusCodeID] FOREIGN KEY (StatusCodeID) REFERENCES StatusCodes(StatusCodeID),
	CONSTRAINT [FK_Bugs_UserID_BugLog] FOREIGN KEY (UserID) REFERENCES Users(UserID),
	CONSTRAINT [FK_Bugs_BugID] FOREIGN KEY (BugID) REFERENCES Bugs(BugID)



)
