CREATE TABLE [dbo].[Bugs]
(
	[BugID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[AppID] INT NOT NULL,
	[UserID] INT NOT NULL,
	[BugSignOff] INT NOT NULL,
	[BugDate] DATETIME NOT NULL,
	[BugDesc] NVARCHAR(40) NOT NULL,
	[BugDetails] TEXT NOT NULL,
	[RepSteps] TEXT,
	[FixDate] DATETIME,
	CONSTRAINT [FK_Bugs_AppId] FOREIGN KEY (AppID) REFERENCES Applications(AppID),
	CONSTRAINT [FK_Bugs_UserID] FOREIGN KEY (UserID) REFERENCES Users(UserID),
	CONSTRAINT [FK_Bugs_BugSignOff] FOREIGN KEY (BugSignOff) REFERENCES Users(UserID)
)
